/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  TrackedProduct as PrismaTrackedProduct,
  PriceHistory as PrismaPriceHistory,
  Store as PrismaStore,
  User as PrismaUser,
} from "@prisma/client";

export class TrackedProductServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TrackedProductCountArgs, "select">
  ): Promise<number> {
    return this.prisma.trackedProduct.count(args);
  }

  async trackedProducts(
    args: Prisma.TrackedProductFindManyArgs
  ): Promise<PrismaTrackedProduct[]> {
    return this.prisma.trackedProduct.findMany(args);
  }
  async trackedProduct(
    args: Prisma.TrackedProductFindUniqueArgs
  ): Promise<PrismaTrackedProduct | null> {
    return this.prisma.trackedProduct.findUnique(args);
  }
  async createTrackedProduct(
    args: Prisma.TrackedProductCreateArgs
  ): Promise<PrismaTrackedProduct> {
    return this.prisma.trackedProduct.create(args);
  }
  async updateTrackedProduct(
    args: Prisma.TrackedProductUpdateArgs
  ): Promise<PrismaTrackedProduct> {
    return this.prisma.trackedProduct.update(args);
  }
  async deleteTrackedProduct(
    args: Prisma.TrackedProductDeleteArgs
  ): Promise<PrismaTrackedProduct> {
    return this.prisma.trackedProduct.delete(args);
  }

  async findPriceHistories(
    parentId: string,
    args: Prisma.PriceHistoryFindManyArgs
  ): Promise<PrismaPriceHistory[]> {
    return this.prisma.trackedProduct
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .priceHistories(args);
  }

  async getStore(parentId: string): Promise<PrismaStore | null> {
    return this.prisma.trackedProduct
      .findUnique({
        where: { id: parentId },
      })
      .store();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.trackedProduct
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
