/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TrackedProductService } from "../trackedProduct.service";
import { TrackedProductCreateInput } from "./TrackedProductCreateInput";
import { TrackedProduct } from "./TrackedProduct";
import { TrackedProductFindManyArgs } from "./TrackedProductFindManyArgs";
import { TrackedProductWhereUniqueInput } from "./TrackedProductWhereUniqueInput";
import { TrackedProductUpdateInput } from "./TrackedProductUpdateInput";
import { PriceHistoryFindManyArgs } from "../../priceHistory/base/PriceHistoryFindManyArgs";
import { PriceHistory } from "../../priceHistory/base/PriceHistory";
import { PriceHistoryWhereUniqueInput } from "../../priceHistory/base/PriceHistoryWhereUniqueInput";

export class TrackedProductControllerBase {
  constructor(protected readonly service: TrackedProductService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TrackedProduct })
  async createTrackedProduct(
    @common.Body() data: TrackedProductCreateInput
  ): Promise<TrackedProduct> {
    return await this.service.createTrackedProduct({
      data: {
        ...data,

        store: data.store
          ? {
              connect: data.store,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        currentPrice: true,
        desiredDiscountPercentage: true,
        id: true,
        initialPrice: true,
        isActive: true,
        productUrl: true,

        store: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TrackedProduct] })
  @ApiNestedQuery(TrackedProductFindManyArgs)
  async trackedProducts(
    @common.Req() request: Request
  ): Promise<TrackedProduct[]> {
    const args = plainToClass(TrackedProductFindManyArgs, request.query);
    return this.service.trackedProducts({
      ...args,
      select: {
        createdAt: true,
        currentPrice: true,
        desiredDiscountPercentage: true,
        id: true,
        initialPrice: true,
        isActive: true,
        productUrl: true,

        store: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TrackedProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async trackedProduct(
    @common.Param() params: TrackedProductWhereUniqueInput
  ): Promise<TrackedProduct | null> {
    const result = await this.service.trackedProduct({
      where: params,
      select: {
        createdAt: true,
        currentPrice: true,
        desiredDiscountPercentage: true,
        id: true,
        initialPrice: true,
        isActive: true,
        productUrl: true,

        store: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TrackedProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTrackedProduct(
    @common.Param() params: TrackedProductWhereUniqueInput,
    @common.Body() data: TrackedProductUpdateInput
  ): Promise<TrackedProduct | null> {
    try {
      return await this.service.updateTrackedProduct({
        where: params,
        data: {
          ...data,

          store: data.store
            ? {
                connect: data.store,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          currentPrice: true,
          desiredDiscountPercentage: true,
          id: true,
          initialPrice: true,
          isActive: true,
          productUrl: true,

          store: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TrackedProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTrackedProduct(
    @common.Param() params: TrackedProductWhereUniqueInput
  ): Promise<TrackedProduct | null> {
    try {
      return await this.service.deleteTrackedProduct({
        where: params,
        select: {
          createdAt: true,
          currentPrice: true,
          desiredDiscountPercentage: true,
          id: true,
          initialPrice: true,
          isActive: true,
          productUrl: true,

          store: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/priceHistories")
  @ApiNestedQuery(PriceHistoryFindManyArgs)
  async findPriceHistories(
    @common.Req() request: Request,
    @common.Param() params: TrackedProductWhereUniqueInput
  ): Promise<PriceHistory[]> {
    const query = plainToClass(PriceHistoryFindManyArgs, request.query);
    const results = await this.service.findPriceHistories(params.id, {
      ...query,
      select: {
        capturedAt: true,
        createdAt: true,
        id: true,
        price: true,

        trackedProduct: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/priceHistories")
  async connectPriceHistories(
    @common.Param() params: TrackedProductWhereUniqueInput,
    @common.Body() body: PriceHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      priceHistories: {
        connect: body,
      },
    };
    await this.service.updateTrackedProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/priceHistories")
  async updatePriceHistories(
    @common.Param() params: TrackedProductWhereUniqueInput,
    @common.Body() body: PriceHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      priceHistories: {
        set: body,
      },
    };
    await this.service.updateTrackedProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/priceHistories")
  async disconnectPriceHistories(
    @common.Param() params: TrackedProductWhereUniqueInput,
    @common.Body() body: PriceHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      priceHistories: {
        disconnect: body,
      },
    };
    await this.service.updateTrackedProduct({
      where: params,
      data,
      select: { id: true },
    });
  }
}
