/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TrackedProduct } from "./TrackedProduct";
import { TrackedProductCountArgs } from "./TrackedProductCountArgs";
import { TrackedProductFindManyArgs } from "./TrackedProductFindManyArgs";
import { TrackedProductFindUniqueArgs } from "./TrackedProductFindUniqueArgs";
import { CreateTrackedProductArgs } from "./CreateTrackedProductArgs";
import { UpdateTrackedProductArgs } from "./UpdateTrackedProductArgs";
import { DeleteTrackedProductArgs } from "./DeleteTrackedProductArgs";
import { PriceHistoryFindManyArgs } from "../../priceHistory/base/PriceHistoryFindManyArgs";
import { PriceHistory } from "../../priceHistory/base/PriceHistory";
import { Store } from "../../store/base/Store";
import { User } from "../../user/base/User";
import { TrackedProductService } from "../trackedProduct.service";
@graphql.Resolver(() => TrackedProduct)
export class TrackedProductResolverBase {
  constructor(protected readonly service: TrackedProductService) {}

  async _trackedProductsMeta(
    @graphql.Args() args: TrackedProductCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TrackedProduct])
  async trackedProducts(
    @graphql.Args() args: TrackedProductFindManyArgs
  ): Promise<TrackedProduct[]> {
    return this.service.trackedProducts(args);
  }

  @graphql.Query(() => TrackedProduct, { nullable: true })
  async trackedProduct(
    @graphql.Args() args: TrackedProductFindUniqueArgs
  ): Promise<TrackedProduct | null> {
    const result = await this.service.trackedProduct(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TrackedProduct)
  async createTrackedProduct(
    @graphql.Args() args: CreateTrackedProductArgs
  ): Promise<TrackedProduct> {
    return await this.service.createTrackedProduct({
      ...args,
      data: {
        ...args.data,

        store: args.data.store
          ? {
              connect: args.data.store,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => TrackedProduct)
  async updateTrackedProduct(
    @graphql.Args() args: UpdateTrackedProductArgs
  ): Promise<TrackedProduct | null> {
    try {
      return await this.service.updateTrackedProduct({
        ...args,
        data: {
          ...args.data,

          store: args.data.store
            ? {
                connect: args.data.store,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TrackedProduct)
  async deleteTrackedProduct(
    @graphql.Args() args: DeleteTrackedProductArgs
  ): Promise<TrackedProduct | null> {
    try {
      return await this.service.deleteTrackedProduct(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [PriceHistory], { name: "priceHistories" })
  async findPriceHistories(
    @graphql.Parent() parent: TrackedProduct,
    @graphql.Args() args: PriceHistoryFindManyArgs
  ): Promise<PriceHistory[]> {
    const results = await this.service.findPriceHistories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Store, {
    nullable: true,
    name: "store",
  })
  async getStore(
    @graphql.Parent() parent: TrackedProduct
  ): Promise<Store | null> {
    const result = await this.service.getStore(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(
    @graphql.Parent() parent: TrackedProduct
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
