/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StoreService } from "../store.service";
import { StoreCreateInput } from "./StoreCreateInput";
import { Store } from "./Store";
import { StoreFindManyArgs } from "./StoreFindManyArgs";
import { StoreWhereUniqueInput } from "./StoreWhereUniqueInput";
import { StoreUpdateInput } from "./StoreUpdateInput";
import { TrackedProductFindManyArgs } from "../../trackedProduct/base/TrackedProductFindManyArgs";
import { TrackedProduct } from "../../trackedProduct/base/TrackedProduct";
import { TrackedProductWhereUniqueInput } from "../../trackedProduct/base/TrackedProductWhereUniqueInput";

export class StoreControllerBase {
  constructor(protected readonly service: StoreService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Store })
  async createStore(@common.Body() data: StoreCreateInput): Promise<Store> {
    return await this.service.createStore({
      data: data,
      select: {
        baseUrl: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        priceSelector: true,
        scrapingMethod: true,
        titleSelector: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Store] })
  @ApiNestedQuery(StoreFindManyArgs)
  async stores(@common.Req() request: Request): Promise<Store[]> {
    const args = plainToClass(StoreFindManyArgs, request.query);
    return this.service.stores({
      ...args,
      select: {
        baseUrl: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        priceSelector: true,
        scrapingMethod: true,
        titleSelector: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Store })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async store(
    @common.Param() params: StoreWhereUniqueInput
  ): Promise<Store | null> {
    const result = await this.service.store({
      where: params,
      select: {
        baseUrl: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        priceSelector: true,
        scrapingMethod: true,
        titleSelector: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Store })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStore(
    @common.Param() params: StoreWhereUniqueInput,
    @common.Body() data: StoreUpdateInput
  ): Promise<Store | null> {
    try {
      return await this.service.updateStore({
        where: params,
        data: data,
        select: {
          baseUrl: true,
          createdAt: true,
          id: true,
          isActive: true,
          name: true,
          priceSelector: true,
          scrapingMethod: true,
          titleSelector: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Store })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStore(
    @common.Param() params: StoreWhereUniqueInput
  ): Promise<Store | null> {
    try {
      return await this.service.deleteStore({
        where: params,
        select: {
          baseUrl: true,
          createdAt: true,
          id: true,
          isActive: true,
          name: true,
          priceSelector: true,
          scrapingMethod: true,
          titleSelector: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/trackedProducts")
  @ApiNestedQuery(TrackedProductFindManyArgs)
  async findTrackedProducts(
    @common.Req() request: Request,
    @common.Param() params: StoreWhereUniqueInput
  ): Promise<TrackedProduct[]> {
    const query = plainToClass(TrackedProductFindManyArgs, request.query);
    const results = await this.service.findTrackedProducts(params.id, {
      ...query,
      select: {
        createdAt: true,
        currentPrice: true,
        desiredDiscountPercentage: true,
        id: true,
        initialPrice: true,
        isActive: true,
        productUrl: true,

        store: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/trackedProducts")
  async connectTrackedProducts(
    @common.Param() params: StoreWhereUniqueInput,
    @common.Body() body: TrackedProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trackedProducts: {
        connect: body,
      },
    };
    await this.service.updateStore({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/trackedProducts")
  async updateTrackedProducts(
    @common.Param() params: StoreWhereUniqueInput,
    @common.Body() body: TrackedProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trackedProducts: {
        set: body,
      },
    };
    await this.service.updateStore({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/trackedProducts")
  async disconnectTrackedProducts(
    @common.Param() params: StoreWhereUniqueInput,
    @common.Body() body: TrackedProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trackedProducts: {
        disconnect: body,
      },
    };
    await this.service.updateStore({
      where: params,
      data,
      select: { id: true },
    });
  }
}
