/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { EnumStoreScrapingMethod } from "./EnumStoreScrapingMethod";
import { TrackedProductListRelationFilter } from "../../trackedProduct/base/TrackedProductListRelationFilter";

@InputType()
class StoreWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  baseUrl?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isActive?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  priceSelector?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumStoreScrapingMethod,
  })
  @IsEnum(EnumStoreScrapingMethod)
  @IsOptional()
  @Field(() => EnumStoreScrapingMethod, {
    nullable: true,
  })
  scrapingMethod?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  titleSelector?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TrackedProductListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TrackedProductListRelationFilter)
  @IsOptional()
  @Field(() => TrackedProductListRelationFilter, {
    nullable: true,
  })
  trackedProducts?: TrackedProductListRelationFilter;
}

export { StoreWhereInput as StoreWhereInput };
