/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsBoolean,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { EnumStoreScrapingMethod } from "./EnumStoreScrapingMethod";
import { TrackedProductCreateNestedManyWithoutStoresInput } from "./TrackedProductCreateNestedManyWithoutStoresInput";
import { Type } from "class-transformer";

@InputType()
class StoreCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  baseUrl?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  priceSelector?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumStoreScrapingMethod,
  })
  @IsEnum(EnumStoreScrapingMethod)
  @IsOptional()
  @Field(() => EnumStoreScrapingMethod, {
    nullable: true,
  })
  scrapingMethod?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  titleSelector?: string | null;

  @ApiProperty({
    required: false,
    type: () => TrackedProductCreateNestedManyWithoutStoresInput,
  })
  @ValidateNested()
  @Type(() => TrackedProductCreateNestedManyWithoutStoresInput)
  @IsOptional()
  @Field(() => TrackedProductCreateNestedManyWithoutStoresInput, {
    nullable: true,
  })
  trackedProducts?: TrackedProductCreateNestedManyWithoutStoresInput;
}

export { StoreCreateInput as StoreCreateInput };
